In [82]:
"""
my class for codevs zombie codin game challenge.
"""

import numpy as np
import sys
import math
import random 
import time




class Apocalypse:
    """
    Class for simulating zombie pursuit of human 
    """

    def __init__(self,zombie_list = None, human_list = None):
        """
        to initialize a simulation to caluclate best move
        
        """
        self.thisscore=0
        self.target=[0,0]
        self.bestfirstgo=[0,0]
        self.firsttar=()
        self.need_strat=True
        self._player_dist=[]
        self.t1=0
        self.t0=0
        self.firstgo=True
        if  zombie_list != None:
            self._zombie_list = list(zombie_list)
        else:
            self._zombie_list = []
        if human_list != None:
            self._human_list = list(human_list)  
        else:
            self._human_list = []
        
    def clear(self):
        """
        to 
        """
  #      self.firstgo=True
        self._zombie_list=[]
        self._human_list=[]
        self.thisscore=0
        
    def add_zombie(self,zombie_id, zombie_x, zombie_y, zombie_xnext, zombie_ynext):
        """
        Add zombie to the zombie list
        """
        #the 0's at end are the distance to closest human and index number of human in list.
        self._zombie_list.append([zombie_id, zombie_x, zombie_y, zombie_xnext, zombie_ynext,0,0])
        
                
    def num_zombies(self):
        """
        Return number of zombies
        """
        self._zombie_list=list(self._zombie_list)      
        if self._zombie_list:
            zomnum=len(self._zombie_list)
            return (zomnum)
        else:
            return(0)
          

    def add_human(self,human_id, human_x, human_y):
        """
        Add human to the human list
        """
        self._human_list=list(self._human_list)
        self._human_list.append([human_id, human_x, human_y,0])
    
    def ini_player(self,x,y):
        self.player_x=x
        self.player_y=y
    
    
    def add_player(self):
        
        
        
        self._human_list.append([-1, self.player_x, self.player_y,0])
        self._human_list=np.array((self._human_list))
        
        
    def num_humans(self):
        """
        Return number of humans,also player is added to this list
        """
        
        if self._human_list:
            
            return len(self._human_list)
            
    
    def score(self,numbershot):
        s=[1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765,10946,17711,
           28657,46368,75025,121393,196418]

        self.thisscore+=(s[numbershot]*(((len(self._human_list)-1)**2)*10))
  #      print((s[numbershot]*(((len(self._human_list)-1)**2)*10)),"score!!")
    def calc_dist(self):

#        self.t0 += time.time()
        self._player_dist=[]
        """
        for ind,val in enumerate(self._zombie_list):
            _d=self._human_list[:,1:3]-val[1:3]
            _dist_fac=_d*_d
            _mini_tot=np.sum(_dist_fac,axis=1)

            _mini_dis=min(_mini_tot)
            _mini_index=(np.where(_mini_tot==_mini_dis))[0][0]
            self._zombie_list[ind][5:]=int(math.sqrt(_mini_dis)),_mini_index
        
        """
        self._zombie_listi=np.array(self._zombie_list) 
        ##remove this array swap
   
        _b= np.array(self._human_list[:,1:3])
        _d=[]
        for i in range(self.num_zombies()):
            _d.append(_b)
        _d=np.array(_d)
        _d=_d.transpose((1, 0, 2))
        _d=_d-self._zombie_listi[:,1:3]
        _dist_fac=_d*_d
        _mini_tot=np.sum(_dist_fac,axis=2)
        _mini_dis=_mini_tot.min(axis=0)
        _mini_index=np.where(_mini_tot==_mini_tot.min(axis=0))
        _mini_dis=np.rint(np.sqrt(_mini_dis))
    
        listOfCordinates = np.array([_mini_index[0], _mini_index[1]],dtype=np.int)
        
        listOfCordinates=listOfCordinates.transpose((1,0))
        
        lisorted= listOfCordinates[listOfCordinates[:,1].argsort()]
        _mini_dis=np.transpose(_mini_dis)


        self._zombie_listi[:,5]=_mini_dis
        self._zombie_listi[:,6]=lisorted[:,0]
        self._zombie_list=self._zombie_listi.tolist()
        
#        self.t1 += time.time()
        
        
    def do_move(self):
        
        ## starts off calculating distance between all zombies and humans, then dose the unit veto
        ## to closest one.
        
        if 1==2:
        
#        if self.firstgo==True:           
            self._zombie_list=np.array(self._zombie_list)   
            self._zombie_list[:,1:3]=self._zombie_list[:,3:5]          
            
        else:
  
            for ind,val in enumerate(self._zombie_list):
                if val[5]<400:
                    val[1:3]=self._human_list[int(val[6])][1:3]
                else:
                    z=val[1:3]-self._human_list[int(val[6])][1:3]
                    v=z*z
                    vec1=(z/math.sqrt(sum(v)))*400
                    vec1 = np.round(vec1, decimals=0)
                    val[1:3]=val[1:3]-vec1
                    
                    
        
        
        if self.need_strat==True:
            test.stratergy()
        ##move player
        if self.target[0]==-1:
        
            
            dx,dy=int(self.target[1])-self.player_x,int(self.target[2])-self.player_x
            
        else:
            ind=[i for i,j in enumerate(self._zombie_list) if j[0]==self.target[0]]

            dx,dy=int(self._zombie_list[(ind[0])][1])-self.player_x,int(self._zombie_list[(ind[0])][2])-self.player_y
        l=math.sqrt((dx*dx)+(dy*dy))
        
        if l>0:
            self.player_x+=int((dx*2000)/l)
            self.player_y+=int((dy*2000)/l)    
            
        self._human_list[-1][1:3]=self.player_x,self.player_y
        
        self.timeteststart+=time.time()
        for ind,val in enumerate(self._zombie_list):
            ##to build array for player to zombie distance, for zombie killing
            _play_di=np.array(([self.player_x,self.player_y]))-val[1:3]

            _play_dist=int(math.sqrt((np.sum((_play_di*_play_di),axis=0))))
            self._player_dist.append(_play_dist)

            
        self.timetestend+=time.time()    
#        print(self._player_dist,"dist.........")
        savelist=[]
        k_count=0

        for ind,val in enumerate(self._player_dist):
            ## zombie killing
            
            if val>2000:
                savelist.append(ind)
                
                
            else:
                k_count+=1
        if k_count>0:
            test.score(k_count)
        
        saver=[(self._zombie_list[i]) for i in savelist]
        for i in savelist:
            if self._zombie_list[i][0]==self.target[0]:
                self.need_strat=False
            else:
                self.need_strat=True 
                break
        self._zombie_list=saver
        
        kill_list=[j[6] for i,j in enumerate(self._zombie_list) if (j[1:2]-self._human_list[int(j[6])][1:2])==0 and (j[2:3]-self._human_list[int(j[6])][2:3])==0]    
                
        kill_list=set(kill_list)
        before=self._human_list.copy()
        before2=self._zombie_list.copy()
        for i in sorted(kill_list, reverse=True):
            print(self._human_list,"hums",kill_list,"thekills")
            self._human_list=np.delete(self._human_list,i ,axis=0)
        
       
           
            
 #       print(len(self._human_list),"H")
 #       print(len(self._zombie_list),"C")
    
        self.firstgo=False      
        if len(self._human_list)<2:
            self.thisscore=0

    
    
    def stratergy(self):
 
        if random.randint(1, 7)==2:
            mx=10*(random.randint(-180, 180))
            my=10*(random.randint(-180, 180))
            tx=self.player_x+mx
            ty=self.player_y+my
            if tx>1600:tx=16000
            if ty>9000:ty=9000
            if tx<0:tx=0
            if ty<0:ty=0
            self.target=[-1,tx,ty]
            if self.firstgo==True:
                self.firsttar=(mx,my)

        else:
            t=random.randint(0,(self.num_zombies()-1))
            self.target[0]=self._zombie_list[t][0]
            if self.firstgo==True:
                self.firsttar=(self._zombie_list[t][3:5])
                
            self.need_strat=False
                
                
    def run(self):
        
        while len(self._human_list)>1 and len(self._zombie_list)>0:    
            test.calc_dist()
            test.do_move()
        self.tots+=1
        if len(self._human_list)>1:
            self.finish+=1
            print("finished ratio =",self.finish/self.tots,)
            if self.thisscore>self.bestfirstgo[0]:
                self.bestfirstgo[0]=self.thisscore
                self.bestfirstgo[1]=self.firsttar
  #              print(self.firsttar)
            
    def repeat(self):
        go=0
        self.t0 = time.time()
        self.finish=0
        self.died=0
        self.tots=0
        self.timeteststart=0
        self.timetestend=0
        while go<1000:
            
            test.settest()
            test.run()
            go+=1
            print (self.bestfirstgo[0])   
        print(self.bestfirstgo)
        self.t1 = time.time()
        print("Time:",self.t1-self.t0)
        print("Section time",self.timetestend-self.timeteststart)
    
    def settest(self):
        test.clear()
        test.add_zombie(13, 4720, 2000, 4720, 2000)
        test.add_zombie(16, 720, 1000, 720, 1000)
        test.add_zombie(15, 12120, 7000, 12120, 7000)
        test.add_zombie(14, 1120, 4000, 1120, 4000)
        test.add_zombie(12, 6120, 1000, 7120, 1000)
        test.add_zombie(11, 120, 4000, 120, 4000)
        test.add_zombie(10, 140, 4100, 140, 4100)
        test.add_zombie(9, 160, 4200, 160, 4200)
        test.add_zombie(8, 180, 4300, 180, 4300)
        test.add_zombie(7, 720, 900, 720, 900)
        test.add_zombie(6, 730, 1010, 730, 1010)
        test.add_zombie(5, 12000, 8000, 12000, 8000)
        test.add_zombie(4, 12100, 8100, 12100, 8100)
        test.add_zombie(3, 12200, 7900, 12200, 7900)
        test.add_zombie(2, 12100, 8200, 12100, 8200)
        test.add_zombie(1, 12200, 3800, 12200, 7800)
        
        test.add_zombie(0, 4000, 800, 4000, 800)
        test.add_human(0, 14000, 8000)
        test.add_human(4, 10000, 1000)
        test.add_human(1, 400, 800)
        test.add_human(2, 5000, 1000)
  #      test.add_human(3, 5000, 7000)
        test.ini_player(5000,5800)
        test.add_player()


test=Apocalypse()

test.settest()
#test.calc_dist()
test.repeat()






#test.run()    
#test.calc_dist()
#test.do_move()
#test.calc_dist()
#test.do_move()







[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4755  3816     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1820  3224     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7383  3042     0]] hums {0.0} thekills
finished ratio = 1.0
1000
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3286  3761     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3919  3018     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  9662  3485     0]] hums {0.0} thekills
1000
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6999  5

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:241: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future


[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9977  4978     0]] hums {0.0} thekills
finished ratio = 0.2631578947368421
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6871  4168     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3373  2615     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6988  3939     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6926  6337     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7281  5641     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7550  5116     0]] hums {0.0} thekills
[[    4

finished ratio = 0.2545454545454545
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6966  6165     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  5431  2732     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  8975  2907     0]] hums {0.0} thekills
[[    2  5000  1000     0]
 [   -1 11259  3409     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6913  6381     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4015  3627     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3859  4156     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4161  2350     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [

 [   -1  7080  5649     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1 10715  6072     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7239  4148     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6999  5764     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7168  4196     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  5220  1829     0]] hums {0.0} thekills
finished ratio = 0.27058823529411763
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3166  5003     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3185  4946     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -

 [   -1  3166  5003     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6988  6175     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4404  4185     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7243  3537     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4918  3802     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3222  1804     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10189  4336     0]] hums {0.0} thekills
finished ratio = 0.2894736842105263
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3154  5033     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  

 [   -1 10739  3113     0]] hums {1.0} thekills
finished ratio = 0.3055555555555556
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1199  5970     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  5000  7214     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8575  4246     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7333  5667     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7351  5614     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8529  4124     0]] hums {

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7752  5234     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7823  4788     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7971  4698     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  5296  3823     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  8814  5724     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  8949  5493     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8930  5674     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4918  3802     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1747  2851     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9269  5563     0]] hums {0.0} thekills
finished ratio = 0.3137254901960784
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7854  4408     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3909  3755     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7941  4673     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  5296  3823     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9052  2686     0]] 

finished ratio = 0.31196581196581197
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7445  5248     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  5328  2752     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  5283  4185     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3553  4731     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  2438  2080     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  9687  4942     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 

finished ratio = 0.30566037735849055
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3031  4147     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  6024  1940     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  9029  4990     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3141  5064     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1016  2299     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4506  1224     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1 11148  5676     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 

[[    4 10000  1000     0]
 [   -1  7376  2791     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1   594  3661     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  1663  6111     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  5918  5796     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6913  6381     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7001  6146     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7054  5985     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4244  3207     0]] hums {0.0} thek

 [   -1  4028  4016     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4173  2774     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7830  4387     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6966  6165     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10817  5087     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1 10541  5733     0]] hums {0.0} thekills
finished ratio = 0.30275229357798167
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3141  5064     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3381  4591     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -

finished ratio = 0.29608938547486036
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6811  5377     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  6889  5028     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6996  4936     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6917  6369     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3359  4561     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4077  1812     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1 10648  4613     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1750  1287     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7378  5016     0]] hums {0.0} thekills
finished ratio = 0.2948717948717949
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6936  3547     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3837  2609     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  3971  2359     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4918  3802     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3515  1773     0]] 

finished ratio = 0.2973621103117506
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6913  6381     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3819  4017     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4156  2952     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7644  3652     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3652  3960     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7381  5405     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8503  2729     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [

 [   -1  9089  5267     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3179  4974     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6994  4637     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3008  4315     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7441  3993     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6967  6157     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7289  5544     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3968  3521     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4514  2878     0]] hums {0.0} thekills
3420
[[    0 14000  80

finished ratio = 0.2981366459627329
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6917  6369     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4234  4128     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  1674  1754     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8794  3746     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6999  5854     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  5085  3055     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4946  4130     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6409  3338     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1129  1222     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  5085   713     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  5389  4006     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6913  6381     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6949  5308     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3155  4051     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7207  4793     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3166  5003     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1

 [   -1 11835  2819     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9700  5603     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9011  4093     0]] hums {0.0} thekills
[[   2 5000 1000    0]
 [  -1 9367  971    0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7310  4366     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1 10744  2401     0]] hums {0.0} thekills
finished ratio = 0.2888086642599278
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   

 [   -1  7063  5656     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7929  4609     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  3620  1917     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6917  6369     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3243  4791     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7163  5298     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4890  3870     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4918  3802     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4913  3903     0]] hums {2.0} thekills
[[    0 14000  8000   

 [   -1  7825  3026     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6809  5442     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4303  2626     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4407  2846     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6946  6260     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7759  5162     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7358  3802     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  3167  3697     0]] hums {0.0} thekills
3420
[[    0 14000  80

 [   -1  8084  3570     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3154  5033     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  5965  2843     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  9313  5028     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  9334  4236     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6926  6337     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7098  5806     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7214  4734     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1 10159  5175     0]] hums {0.0} thekills
3420
[[    0 14000  80

 [   -1 11094  3229     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4215  3587     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7997  4111     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1 11257  6536     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6917  6369     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3646  4136     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7611  4598     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  3811  3811     0]] hums {0.0} thekills
3420
[[    0 14000  80

[[    4 10000  1000     0]
 [   -1 10256  3848     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  4755  3816     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6197  2675     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6337  3127     0]] hums {0.0} thekills
finished ratio = 0.2865248226950355
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6838  5330     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4059  3569     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6470  3286     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [

[[    4 10000  1000     0]
 [   -1  3392  4274     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  5296  3823     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10160  5353     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10134  4099     0]] hums {0.0} thekills
[[   2 5000 1000    0]
 [  -1 9535 3225    0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  6951  4818     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1 10328  2695     0]] hums {0.0} thekills
finished ratio = 0.2855191256830601
3420
[[    0 14000  8000     0]
 [    4 10

 [   -1  6963  5362     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3392  4149     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7978  4661     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7028  6056     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  8333  3587     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  5000  2152     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3561  4595     0]] hums {2.0} thekills
[[    0 14000  8000   

 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4233  4145     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4879  2562     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8407  4472     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6965  6169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3282  4613     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4147  3667     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  9623  4752     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3179  4974     0]] hums {2} thekills
[[    0 14000  8000     

 [   -1  6966  6165     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3518  4361     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  4238  3522     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1 11650  6526     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3154  5033     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3265  4754     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3828  3874     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4870  2165     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3166  5003     0]] hums {2} thekills
[[    0 14000  8000     

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  5083  3447     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  8700  4299     0]] hums {0.0} thekills
finished ratio = 0.2902467685076381
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7293  5507     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3743  3916     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8086  4628     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 

finished ratio = 0.2917620137299771
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7067  5993     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  3497  4218     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  8024  4728     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6978  6094     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10877  6821     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7542  4615     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  7636  1983     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [

 [   -1  6907  6399     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1 10815  7215     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7824  4621     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  4687  3615     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3166  5003     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3676  3202     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  6344  2636     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6027  3401     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  9244  3187     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  8882  3880     0]] hums {0.0} thekills
finished ratio = 0.2890792291220557
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6913  6381     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7751  4869     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7633  5148     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6470  2117     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6997  5898     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  8077  5013     0]] 

 [   -1  5214  5044     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6050  1991     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6999  5849     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  8379  3643     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  4602  1213     0]] hums {0.0} thekills
finished ratio = 0.28790983606557374
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  6897  5169     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  7057  4905     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7675  4152     0]] hums {0.0} thekills
finished ratio = 0.28863868986693964
3420
[[    0 14000  800

[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  3187  2599     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  7179  2372     0]] hums {0.0} thekills
finished ratio = 0.2864321608040201
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  5261  3066     0]] hums {2.0} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [   -1  6595  2301     0]] hums {0.0} thekills
[[    4 10000  1000     0]
 [   -1  6746  3357     0]] hums {0.0} thekills
3420
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    1   400   800     0]
 [    2  5000  1000     0]
 [   -1  3646  4329     0]] hums {2} thekills
[[    0 14000  8000     0]
 [    4 10000  1000     0]
 [    2  5000  1000     0]
 [   -1  1152  2149     0]] 

In [373]:
import numpy as np
a=np.array(([1,2,3],[2,3,5],[4,5,6],[7,8,9]))
b=np.array((1,3,5))
c=np.array(([0,0,0],[0,0,0],[0,0,0],[0,0,0]))
#c[:,1:]=a[:,0:2]-b[1:]
b=a[:,1:3]
print(b)
print(np.sum(b,axis=1))
np.where(b)
#print(min(b))
#d=np.where(b==(min(b)))
#print(d[0][0])
(0, 2)
(0, 6)
(2, 1)
(2, 3)
(2, 5)
(3, 0)
(3, 4)
(3, 7)
0.0019986629486083984
0.0019979476928710938

[[2 3]
 [3 5]
 [5 6]
 [8 9]]
[ 5  8 11 17]


0.0019979476928710938

In [98]:
result = numpy.where(arr2D == numpy.amin(arr2D))

NameError: name 'numpy' is not defined

In [313]:
p=[[1,7],[1,2],[5,6],[3,4]]

print(p)

[[1, 2], [3, 4], [5, 6], [1, 7]]


In [249]:
[[6, 4720, 2000, 4720, 2000, 1038, 3], [6, 720, 1000, 720, 1000, 377, 2], [5, 12120, 7000, 12120, 7000, 2129, 0], [4, 1120, 4000, 1120, 4000, 3280, 2], [3, 7120, 1000, 7120, 1000, 2120, 3], [2, 120, 4000, 120, 4000, 3212, 2], [1, 12000, 8000, 12000, 8000, 2000, 0], [0, 4000, 800, 4000, 800, 1019, 3]]
[[6, 4720, 2000, 4720, 2000, 3212, 3], [6, 720, 1000, 720, 1000, 2129, 2], [5, 12120, 7000, 12120, 7000, 1038, 0], [4, 1120, 4000, 1120, 4000, 3280, 2], [3, 7120, 1000, 7120, 1000, 2000, 3], [2, 120, 4000, 120, 4000, 2120, 2], [1, 12000, 8000, 12000, 8000, 377, 0], [0, 4000, 800, 4000, 800, 1020, 3]]
[[6, 4720, 2000, 4720, 2000, 1038, 0], [6, 720, 1000, 720, 1000, 377, 1], [5, 12120, 7000, 12120, 7000, 2129, 2], [4, 1120, 4000, 1120, 4000, 3280, 3], [3, 7120, 1000, 7120, 1000, 2120, 4], [2, 120, 4000, 120, 4000, 3212, 5], [1, 12000, 8000, 12000, 8000, 2000, 6], [0, 4000, 800, 4000, 800, 1020, 7]]
[[6, 4720, 2000, 4720, 2000, 1038, 3], [6, 720, 1000, 720, 1000, 377, 2], [5, 12120, 7000, 12120, 7000, 2129, 0], [4, 1120, 4000, 1120, 4000, 3280, 2], [3, 7120, 1000, 7120, 1000, 2120, 3], [2, 120, 4000, 120, 4000, 3212, 2], [1, 12000, 8000, 12000, 8000, 2000, 0], [0, 4000, 800, 4000, 800, 1020, 3]]

In [ ]:
[[0, 400, 5000, 30, 5000, 0, 1], [1, 1427.0, 4938.0, 2230, 5000, 1428, 1], [3, 1000, 1000, 4530, 1900, 136, 0]]